name: timingsrc
markdown: kramdown
#highlighter: pygments.rb
highligher: rouge

kramdown:
  input: GFM
  hard_wrap: false
#safe: true
#lsi: false
baseurl: /timingsrc



syntax-highlighting:
  enabled : true
  css: css/syntax.css